"""Text strings for Windows converter."""

OK = 'OK'
EXIT = 'Exit'
QUIT = 'Quit'
CLOSE = 'Close'
COPY = 'Copy'
EVENT = 'Event'
SAVE = 'Save'
NEW = 'New'
EDIT = 'Edit'
DELETE = 'Delete'
ACCEPT = 'Accept'
SELECT = 'Select'
CONFIG = 'Preferences'
ELLIPSIS = ' ...'
LAUNCH = 'Launch'
BUILD = 'Build'
DELETE_PROMPT = 'Are you sure you wish to delete this record?'
DELETE_THESE_ITEMS = 'Are you sure you want to delete these item(s)?'

PROJECT_DEVELOPMENT_DIRECTORY = 'e.g. /home/jeff/projects/bbochat/src'
SOURCE_DIRECTORY = 'e.g. /home/jeff/projects/bbochat/src/bbochat'
IMAGE_DIRECTORY = 'e.g. /home/jeff/projects/bbochat/src/images'
